name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    env:
      GH_TOKEN: ${{ github.token }} # for gh cli

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install OpenSCAD
        run: |
          sudo apt update
          sudo apt install openscad

      - name: Install BOSL2
        run: |
          wget --output-document /tmp/bosl2.tar.gz https://github.com/BelfrySCAD/BOSL2/archive/refs/tags/v2.0.735.tar.gz
          mkdir -p $HOME/.local/share/OpenSCAD/libraries/BOSL2
          tar -xzf /tmp/bosl2.tar.gz --directory=$HOME/.local/share/OpenSCAD/libraries/BOSL2 --strip-components=1

      - name: Build the model
        run: |
          make all

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp model/*.stl artifacts
          cp docs/README.txt artifacts

      - name: Upload the artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vt52
          if-no-files-found: error
          path: artifacts/*

      # Generating PNG doesn't work without X: https://github.com/openscad/openscad/issues/1798
      - name: Build the renders
        if: github.ref == 'refs/heads/main'
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          make preview

      - name: Commit and push the renders
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git fetch origin assets
          git worktree add ../assets-worktree assets
          cp model/*.png ../assets-worktree/
          cd ../assets-worktree
          git add *.png
          git commit -m "Update renders" || true
          git log --stat --max-count=1
          git push origin assets
          cd "$GITHUB_WORKSPACE"
          git worktree remove ../assets-worktree
